作者：朱文斌 教授
日期：2020/08/17
单位：华南理工大学工商管理学院
[在线版本](https://hub.gke.mybinder.org/user/profzhuwb-profzhuwb-bj4369bs/notebooks/tutorial/2020-08-15-Py-8-puzzle/8-puzzle-problem.ipynb)


# 八数码问题 (8 Puzzle Problem)


八数码问题又叫九宫格华容道问题。给定一个 3x3 的九宫格内，有八个1-8的数字和一个空位，每一步可以把空位相邻（上、下、左、右)的数字滑动到空位处，要求用最少的步数把它变成一个目标局面。比如开始局面 $s1$, 目标局面为 $s21$:

把开始局面中空位向上、右、下、左移动一步，得到局面$s2$ $s3$ $s4$ $s5$。把局面$s5$中的空位下移一半得到局面$s13$，再左移一步得到目标局面 $s21$。这个例子只需要移动3步就可以从开始局面到达目标局面。 

![状态图](8-puzzle.jpg)


## 用 State 类描述局面

1. 我们可以用一个 3 行 3 列的二维数组 b 描述一个局面，b\[i\]\[j\] = d 表示数字 d 在第 i 行，第 j 列
2. 用数字 0 表示空位
3. 用两个变量 i,j 记录空位所在的行与列



In [4]:
import numpy as np # 用到 numpy 的数组

# 定义一个叫 State 的类
class State:
    
    # 定义一个构造函数，用传进来的 b,i,j 构造一个局面
    def __init__(self, b, i, j):
        self.b = b
        self.i = i
        self.j = j
    
    # 把局面转换成一个字符串，方便打印输出
    def __str__(self):
        return "空位在第 {0} 行，第 {1} 列\n{2}".format(self.i,self.j,self.b)

# 创建初始局面，会调用构造函数 __init__
s1 = State(b=np.array([[1,2,3],[8,0,4],[7,6,5]]), i=1, j=1)

# 打印初始局面，会调用 s0.__str__ 函数把局面变成字符串
print(s1)

空位在第 1 行，第 1 列
[[1 2 3]
 [8 0 4]
 [7 6 5]]


### 实现移动一步

在 State 类中添加一个 move(mv) 方法，mv = 0,1,2,3 分别表示把空位向上、下、左、右移动一步。该方法返回按照 mv 移动一步后的局面。

1. 移动一步，其实就是把空位与相邻的数字交换位置, python 中可以用 a,b = b,a 来交换两个变量的值
2. 用 ni,nj 表示相邻数字的行与列，mv = 0 时， ni = i - 1, nj = j

| | | |
|---|---|---|
| 1 | 2 (ni,nj) | 3 |
| 8 |   (i, j) | 4 |
| 7 | 6 | 5 |

3. 用 if ... elif ... 对 mv 分情况讨论，先只实现 mv = 0 的情况立即测试一下。初始局面空位上移动一步应该是局面 $s2$


In [1]:
import numpy as np # 用到 numpy 的数组

# 定义一个叫 State 的类
class State:
    
    # 定义一个构造函数，用传进来的 b,i,j 构造一个局面
    def __init__(self, b, i, j):
        self.b = b
        self.i = i
        self.j = j
    
    # 把局面转换成一个字符串，方便打印输出
    def __str__(self):
        return "空位在第 {0} 行，第 {1} 列\n{2}".format(self.i,self.j,self.b)

    # 由当前局面按照 mv 移动一步后得到的局面, mv = 0,1,2,3 分别表示空位向上、右、下、左移动一步。
    def move(self, mv):
        if mv == 0:
            ni = self.i - 1
            nj = self.j
            
            b = np.copy(self.b) # 把局面复制一份，移动不会改变当前局面
            b[ni][nj],b[self.i][self.j] = b[self.i][self.j],b[ni][nj]
            return State(b,ni,nj)
            
    
# 创建初始局面，会调用构造函数 __init__
s1 = State(b=np.array([[1,2,3],[8,0,4],[7,6,5]]), i=1, j=1)

s2 = s1.move(0)
print("初始局面空位上移一步后的局面：")
print(s2)

初始局面空位上移一步后的局面：
空位在第 0 行，第 1 列
[[1 0 3]
 [8 2 4]
 [7 6 5]]


从局面 $s1$ 把空格再上移一步试一下：

In [2]:
print("局面 S2 空位上移一步后的局面：")
print(s2.move(0))

局面 S2 空位上移一步后的局面：
空位在第 -1 行，第 1 列
[[1 6 3]
 [8 2 4]
 [7 0 5]]


In [ ]:
空位的位置在 -1 行， 1 列。0 跑到了第 2 行。程序出错了！！！。暂时不管这个错误，先把 mv = 1, 2, 3 的情况实现一下。

In [3]:
import numpy as np # 用到 numpy 的数组

# 定义一个叫 State 的类
class State:
    
    # 定义一个构造函数，用传进来的 b,i,j 构造一个局面
    def __init__(self, b, i, j):
        self.b = b
        self.i = i
        self.j = j
    
    # 把局面转换成一个字符串，方便打印输出
    def __str__(self):
        return "空位在第 {0} 行，第 {1} 列\n{2}".format(self.i,self.j,self.b)

    # 由当前局面按照 mv 移动一步后得到的局面, mv = 0,1,2,3 分别表示空位向上、右、下、左移动一步。
    def move(self, mv):
        if mv == 0: # 空位上移
            ni = self.i - 1
            nj = self.j
            
            b = np.copy(self.b) # 把局面复制一份，移动不会改变当前局面
            b[ni][nj],b[self.i][self.j] = b[self.i][self.j],b[ni][nj]
            return State(b,ni,nj)
        elif mv == 1: # 空位下移
            ni = self.i + 1
            nj = self.j
            
            b = np.copy(self.b) # 把局面复制一份，移动不会改变当前局面
            b[ni][nj],b[self.i][self.j] = b[self.i][self.j],b[ni][nj]
            return State(b,ni,nj)
        
        elif mv == 2: # 空位左移
            ni = self.i
            nj = self.j - 1
            
            b = np.copy(self.b) # 把局面复制一份，移动不会改变当前局面
            b[ni][nj],b[self.i][self.j] = b[self.i][self.j],b[ni][nj]
            return State(b,ni,nj)
        
        else: # 空位右移
            ni = self.i
            nj = self.j + 1
            
            b = np.copy(self.b) # 把局面复制一份，移动不会改变当前局面
            b[ni][nj],b[self.i][self.j] = b[self.i][self.j],b[ni][nj]
            return State(b,ni,nj)
            
    
# 创建初始局面，会调用构造函数 __init__
s1 = State(b=np.array([[1,2,3],[8,0,4],[7,6,5]]), i=1, j=1)

s2 = s1.move(0)
print("初始局面空位上移一步后的局面：")
print(s2)

print("初始局面空位右移一步后的局面：")
print(s1.move(1))

print("初始局面空位下移一步后的局面：")
print(s1.move(2))

print("初始局面空位左移一步后的局面：")
print(s1.move(3))


初始局面空位上移一步后的局面：
空位在第 0 行，第 1 列
[[1 0 3]
 [8 2 4]
 [7 6 5]]
初始局面空位右移一步后的局面：
空位在第 2 行，第 1 列
[[1 2 3]
 [8 6 4]
 [7 0 5]]
初始局面空位下移一步后的局面：
空位在第 1 行，第 0 列
[[1 2 3]
 [0 8 4]
 [7 6 5]]
初始局面空位左移一步后的局面：
空位在第 1 行，第 2 列
[[1 2 3]
 [8 4 0]
 [7 6 5]]


注意到，mv = 0,1,2,3 最后3行代码都是一样的，可以把它们提取出来移动到move()方法的最后，简化代码。

In [4]:
import numpy as np # 用到 numpy 的数组

# 定义一个叫 State 的类
class State:
    
    # 定义一个构造函数，用传进来的 b,i,j 构造一个局面
    def __init__(self, b, i, j):
        self.b = b
        self.i = i
        self.j = j
    
    # 把局面转换成一个字符串，方便打印输出
    def __str__(self):
        return "空位在第 {0} 行，第 {1} 列\n{2}".format(self.i,self.j,self.b)

    # 由当前局面按照 mv 移动一步后得到的局面, mv = 0,1,2,3 分别表示空位向上、右、下、左移动一步。
    def move(self, mv):
        if mv == 0: # 空位上移
            ni = self.i - 1
            nj = self.j
        elif mv == 1: # 空位下移
            ni = self.i + 1
            nj = self.j
        elif mv == 2: # 空位左移
            ni = self.i
            nj = self.j - 1
        else: # 空位右移
            ni = self.i
            nj = self.j + 1            
            
        b = np.copy(self.b) # 把局面复制一份，移动不会改变当前局面
        b[ni][nj],b[self.i][self.j] = b[self.i][self.j],b[ni][nj]
        return State(b,ni,nj)
            
    
# 创建初始局面，会调用构造函数 __init__
s1 = State(b=np.array([[1,2,3],[8,0,4],[7,6,5]]), i=1, j=1)

s2 = s1.move(0)
print("初始局面空位上移一步后的局面：")
print(s2)

print("初始局面空位右移一步后的局面：")
print(s1.move(1))

print("初始局面空位下移一步后的局面：")
print(s1.move(2))

print("初始局面空位左移一步后的局面：")
print(s1.move(3))


初始局面空位上移一步后的局面：
空位在第 0 行，第 1 列
[[1 0 3]
 [8 2 4]
 [7 6 5]]
初始局面空位右移一步后的局面：
空位在第 2 行，第 1 列
[[1 2 3]
 [8 6 4]
 [7 0 5]]
初始局面空位下移一步后的局面：
空位在第 1 行，第 0 列
[[1 2 3]
 [0 8 4]
 [7 6 5]]
初始局面空位左移一步后的局面：
空位在第 1 行，第 2 列
[[1 2 3]
 [8 4 0]
 [7 6 5]]


注意到，mv=0,1,2,3 我们都是在 (i,j)的基础上加上一个偏移量来得到 ni,nj。

1. 我们可以定义两个数组 di = \[-1,1,0,0\] dj = \[0,0,-1,1\]
2. 无论哪种情况都可以写成 ni,nj = i+di\[mv\], j+dj\[mv\] 进一步简化代码
3. 当移动方式 mv 造成 ni 或者 nj 越界时，返回 None 表示该没有对应的局面

In [5]:
import numpy as np # 用到 numpy 的数组

# 定义一个叫 State 的类
class State:
    
    # 定义一个构造函数，用传进来的 b,i,j 构造一个局面
    def __init__(self, b, i, j):
        self.b = b
        self.i = i
        self.j = j
    
    # 把局面转换成一个字符串，方便打印输出
    def __str__(self):
        return "空位在第 {0} 行，第 {1} 列\n{2}".format(self.i,self.j,self.b)

    # 由当前局面按照 mv 移动一步后得到的局面, mv = 0,1,2,3 分别表示空位向上、右、下、左移动一步。
    def move(self, mv):
        di = [-1,1,0,0]
        dj = [0,0,-1,1]
        ni,nj = self.i+di[mv], self.j+dj[mv]
        
        if ni < 0 or ni > 2 or nj < 0 or nj > 2:
            return None
        
        b = np.copy(self.b) # 把局面复制一份，移动不会改变当前局面
        b[ni][nj],b[self.i][self.j] = b[self.i][self.j],b[ni][nj]
        return State(b,ni,nj)
            
    
# 创建初始局面，会调用构造函数 __init__
s1 = State(b=np.array([[1,2,3],[8,0,4],[7,6,5]]), i=1, j=1)

s2 = s1.move(0)
print("初始局面空位上移一步后的局面：")
print(s2)

print("初始局面空位右移一步后的局面：")
print(s1.move(1))

print("初始局面空位下移一步后的局面：")
print(s1.move(2))

print("初始局面空位左移一步后的局面：")
print(s1.move(3))

print("初始局面空位上移两步后的局面：")
print(s2.move(0))


初始局面空位上移一步后的局面：
空位在第 0 行，第 1 列
[[1 0 3]
 [8 2 4]
 [7 6 5]]
初始局面空位右移一步后的局面：
空位在第 2 行，第 1 列
[[1 2 3]
 [8 6 4]
 [7 0 5]]
初始局面空位下移一步后的局面：
空位在第 1 行，第 0 列
[[1 2 3]
 [0 8 4]
 [7 6 5]]
初始局面空位左移一步后的局面：
空位在第 1 行，第 2 列
[[1 2 3]
 [8 4 0]
 [7 6 5]]
初始局面空位上移两步后的局面：
None


### 找到移动一步能到达的所有局面

添加一个 moves() 函数，它返回一个 list 记录由当前局面可以一步到达的所有局面

In [6]:
import numpy as np # 用到 numpy 的数组

# 定义一个叫 State 的类
class State:
    
    # 定义一个构造函数，用传进来的 b,i,j 构造一个局面
    def __init__(self, b, i, j):
        self.b = b
        self.i = i
        self.j = j
    
    # 把局面转换成一个字符串，方便打印输出
    def __str__(self):
        return "空位在第 {0} 行，第 {1} 列\n{2}".format(self.i,self.j,self.b)

    # 由当前局面按照 mv 移动一步后得到的局面, mv = 0,1,2,3 分别表示空位向上、右、下、左移动一步。
    def move(self, mv):
        di = [-1,1,0,0]
        dj = [0,0,-1,1]
        ni,nj = self.i+di[mv], self.j+dj[mv]
        
        if ni < 0 or ni > 2 or nj < 0 or nj > 2:
            return None
        
        b = np.copy(self.b) # 把局面复制一份，移动不会改变当前局面
        b[ni][nj],b[self.i][self.j] = b[self.i][self.j],b[ni][nj]
        return State(b,ni,nj)
    
    # 返回一个 list 记录由当前局面可以一步到达的所有局面
    def moves(self):
        r = []
        for mv in range(4):
            s = self.move(mv)
            if s is not None:
                r.append(s)
        return r
    
# 创建初始局面，会调用构造函数 __init__
s1 = State(b=np.array([[1,2,3],[8,0,4],[7,6,5]]), i=1, j=1)

print("开始局面移动一步可以到达的局面：")
for s in s1.moves():
    print(s)


开始局面移动一步可以到达的局面：
空位在第 0 行，第 1 列
[[1 0 3]
 [8 2 4]
 [7 6 5]]
空位在第 2 行，第 1 列
[[1 2 3]
 [8 6 4]
 [7 0 5]]
空位在第 1 行，第 0 列
[[1 2 3]
 [0 8 4]
 [7 6 5]]
空位在第 1 行，第 2 列
[[1 2 3]
 [8 4 0]
 [7 6 5]]


### 检查两个局面是否相同

1. 要在 State 中增加一个 __eq__ 方法，用来判断两个局面是否一样
2. 当调用 a == b 时，python 会用 a.__eq__(b) 来替代


In [7]:
import numpy as np # 用到 numpy 的数组

# 定义一个叫 State 的类
class State:
    
    # 定义一个构造函数，用传进来的 b,i,j 构造一个局面
    def __init__(self, b, i, j):
        self.b = b
        self.i = i
        self.j = j
    
    # 把局面转换成一个字符串，方便打印输出
    def __str__(self):
        return "空位在第 {0} 行，第 {1} 列\n{2}".format(self.i,self.j,self.b)

    # 由当前局面按照 mv 移动一步后得到的局面, mv = 0,1,2,3 分别表示空位向上、右、下、左移动一步。
    def move(self, mv):
        di = [-1,1,0,0]
        dj = [0,0,-1,1]
        ni,nj = self.i+di[mv], self.j+dj[mv]
        
        if ni < 0 or ni > 2 or nj < 0 or nj > 2:
            return None
        
        b = np.copy(self.b) # 把局面复制一份，移动不会改变当前局面
        b[ni][nj],b[self.i][self.j] = b[self.i][self.j],b[ni][nj]
        return State(b,ni,nj)
    
    # 返回一个 list 记录由当前局面可以一步到达的所有局面
    def moves(self):
        r = []
        for mv in range(4):
            s = self.move(mv)
            if s is not None:
                r.append(s)
        return r
    
    # 检查 self 是否与 other 是同样局面
    def __eq__(self, other):
        if self.i != other.i or self.j != other.j:
            return False
        return np.array_equal(self.b, other.b)

# 创建目标局面
sF = State(b=np.array([[1,2,3],[8,4,5],[7,0,6]]), i=2, j=1)

# 创建初始局面，会调用构造函数 __init__
s1 = State(b=np.array([[1,2,3],[8,0,4],[7,6,5]]), i=1, j=1)


print("开始局面应该与它自己相同：",s1 == s1)
print("开始局面应该与目标局面不同：",s1 == sF)
print("开始局面右移、下移、左移后应该与目标局面相同：",s1.move(3).move(1).move(2) == sF)



开始局面应该与它自己相同： True
开始局面应该与目标局面不同： False
开始局面右移、下移、左移后应该与目标局面相同： True


## 广度优先搜索 (Breadth First Search)

在状态树树中，从根节点开始，逐层探索每个局面，每层从左到右探索。即按照s0, s1, s2, ..., s20 的顺序进行探索。

1. 用一个队列 q 存放已经发现，即将要套索的局面，开始时 q = \[s0\]
2. 每次把 q 里第一个局面拿出来，进行探索
    1. 比较这个局面是不是目标局面，如果是就找到答案，返回；否则
    2. 把当前局面通过一步能到达的所有局面加到 q 尾部，以后探索
3. 重复步骤 2 直到目标局面找到，或者队列为空


In [8]:
def BFS(s1,sF):
    q = [s1] # 用 list 来实现队列
    count = 0
    while len(q) > 0: # 队列里面还有待探索局面
        f = q.pop(0)  # 拿出队列中的第一个局面
        print("探索局面:{0}".format(count))
        count += 1
        print(f)
        if f == sF:  # 调用 f.__eq__(sF) 检查 f 是否是目标局面
            return f
        q.extend(f.moves()) # 把 f 能一步到达的局面加到队列尾部
    return None

ans = BFS(s1, sF)


探索局面:0
空位在第 1 行，第 1 列
[[1 2 3]
 [8 0 4]
 [7 6 5]]
探索局面:1
空位在第 0 行，第 1 列
[[1 0 3]
 [8 2 4]
 [7 6 5]]
探索局面:2
空位在第 2 行，第 1 列
[[1 2 3]
 [8 6 4]
 [7 0 5]]
探索局面:3
空位在第 1 行，第 0 列
[[1 2 3]
 [0 8 4]
 [7 6 5]]
探索局面:4
空位在第 1 行，第 2 列
[[1 2 3]
 [8 4 0]
 [7 6 5]]
探索局面:5
空位在第 1 行，第 1 列
[[1 2 3]
 [8 0 4]
 [7 6 5]]
探索局面:6
空位在第 0 行，第 0 列
[[0 1 3]
 [8 2 4]
 [7 6 5]]
探索局面:7
空位在第 0 行，第 2 列
[[1 3 0]
 [8 2 4]
 [7 6 5]]
探索局面:8
空位在第 1 行，第 1 列
[[1 2 3]
 [8 0 4]
 [7 6 5]]
探索局面:9
空位在第 2 行，第 0 列
[[1 2 3]
 [8 6 4]
 [0 7 5]]
探索局面:10
空位在第 2 行，第 2 列
[[1 2 3]
 [8 6 4]
 [7 5 0]]
探索局面:11
空位在第 0 行，第 0 列
[[0 2 3]
 [1 8 4]
 [7 6 5]]
探索局面:12
空位在第 2 行，第 0 列
[[1 2 3]
 [7 8 4]
 [0 6 5]]
探索局面:13
空位在第 1 行，第 1 列
[[1 2 3]
 [8 0 4]
 [7 6 5]]
探索局面:14
空位在第 0 行，第 2 列
[[1 2 0]
 [8 4 3]
 [7 6 5]]
探索局面:15
空位在第 2 行，第 2 列
[[1 2 3]
 [8 4 5]
 [7 6 0]]
探索局面:16
空位在第 1 行，第 1 列
[[1 2 3]
 [8 0 4]
 [7 6 5]]
探索局面:17
空位在第 0 行，第 1 列
[[1 0 3]
 [8 2 4]
 [7 6 5]]
探索局面:18
空位在第 2 行，第 1 列
[[1 2 3]
 [8 6 4]
 [7 0 5]]
探索局面:19
空位在第 1 行，第 0 列
[[1 2 3]
 [0 8 4]


### 记录并打印答案

虽然，我们找到了目标局面。我们需要记录如何一步一步到达目标局面。

1. 每个局面加一个 p 属性记录来自那个局面
    1. 在 __init__ 中添加一个 p
    2. 在 move 方法中创建新局面时把新局面的 p 设置为 self
2. 为每个局面创建一个唯一的标识 id 方便输出的时候引用
    1. 在 State 类中增加一个 count 变量，初始值为 0
    2. 在 __init__ 创建一个局面的时候设置 id = count 并把 count 加 1
3. __str__ 方法顺便输出一个局面的 id 及它来自哪个局面


In [9]:
import numpy as np # 用到 numpy 的数组

# 定义一个叫 State 的类
class State:
    
    count = 0
    
    # 定义一个构造函数，用传进来的 b,i,j 构造一个局面
    def __init__(self, b, i, j, p):
        self.b = b
        self.i = i
        self.j = j
        self.p = p
        self.id = State.count
        State.count += 1
    
    # 把局面转换成一个字符串，方便打印输出
    def __str__(self):
        pid = None if self.p is None else self.p.id
        return "id：{0}，来自：{1}。空位在第 {2} 行，第 {3} 列\n{4}".format(self.id, pid, self.i,self.j,self.b)

    # 由当前局面按照 mv 移动一步后得到的局面, mv = 0,1,2,3 分别表示空位向上、右、下、左移动一步。
    def move(self, mv):
        di = [-1,1,0,0]
        dj = [0,0,-1,1]
        ni,nj = self.i+di[mv], self.j+dj[mv]
        
        if ni < 0 or ni > 2 or nj < 0 or nj > 2:
            return None
        
        b = np.copy(self.b) # 把局面复制一份，移动不会改变当前局面
        b[ni][nj],b[self.i][self.j] = b[self.i][self.j],b[ni][nj]
        return State(b,ni,nj,self)
    
    # 返回一个 list 记录由当前局面可以一步到达的所有局面
    def moves(self):
        r = []
        for mv in range(4):
            s = self.move(mv)
            if s is not None:
                r.append(s)
        return r
    
    # 检查 self 是否与 other 是同样局面
    def __eq__(self, other):
        if self.i != other.i or self.j != other.j:
            return False
        return np.array_equal(self.b, other.b)

# 创建目标局面
sF = State(b=np.array([[1,2,3],[8,4,5],[7,0,6]]), i=2, j=1, p=None)

# 创建初始局面，会调用构造函数 __init__
s1 = State(b=np.array([[1,2,3],[8,0,4],[7,6,5]]), i=1, j=1, p=None)

ans = BFS(s1, sF)


探索局面:0
id：1，来自：None。空位在第 1 行，第 1 列
[[1 2 3]
 [8 0 4]
 [7 6 5]]
探索局面:1
id：2，来自：1。空位在第 0 行，第 1 列
[[1 0 3]
 [8 2 4]
 [7 6 5]]
探索局面:2
id：3，来自：1。空位在第 2 行，第 1 列
[[1 2 3]
 [8 6 4]
 [7 0 5]]
探索局面:3
id：4，来自：1。空位在第 1 行，第 0 列
[[1 2 3]
 [0 8 4]
 [7 6 5]]
探索局面:4
id：5，来自：1。空位在第 1 行，第 2 列
[[1 2 3]
 [8 4 0]
 [7 6 5]]
探索局面:5
id：6，来自：2。空位在第 1 行，第 1 列
[[1 2 3]
 [8 0 4]
 [7 6 5]]
探索局面:6
id：7，来自：2。空位在第 0 行，第 0 列
[[0 1 3]
 [8 2 4]
 [7 6 5]]
探索局面:7
id：8，来自：2。空位在第 0 行，第 2 列
[[1 3 0]
 [8 2 4]
 [7 6 5]]
探索局面:8
id：9，来自：3。空位在第 1 行，第 1 列
[[1 2 3]
 [8 0 4]
 [7 6 5]]
探索局面:9
id：10，来自：3。空位在第 2 行，第 0 列
[[1 2 3]
 [8 6 4]
 [0 7 5]]
探索局面:10
id：11，来自：3。空位在第 2 行，第 2 列
[[1 2 3]
 [8 6 4]
 [7 5 0]]
探索局面:11
id：12，来自：4。空位在第 0 行，第 0 列
[[0 2 3]
 [1 8 4]
 [7 6 5]]
探索局面:12
id：13，来自：4。空位在第 2 行，第 0 列
[[1 2 3]
 [7 8 4]
 [0 6 5]]
探索局面:13
id：14，来自：4。空位在第 1 行，第 1 列
[[1 2 3]
 [8 0 4]
 [7 6 5]]
探索局面:14
id：15，来自：5。空位在第 0 行，第 2 列
[[1 2 0]
 [8 4 3]
 [7 6 5]]
探索局面:15
id：16，来自：5。空位在第 2 行，第 2 列
[[1 2 3]
 [8 4 5]
 [7 6 0]]
探索局面:16
id：17，来自：5。空位在第 

从找到的目标局面开始，沿着 p 一路回溯，找到它的前一个局面，用前一个局面的 p 找到再之前的局面。一直到找到开始局面 （它的 p = None)

In [10]:
def findPathFromRoot(s, display=True):
    p = []
    while s is not None:
        p.append(s)
        s = s.p
    p = reversed(p)
    
    if display:
        print("从开始局面到目标局面的路径：")
        for s in p:
            print(s)        
    return p

path = findPathFromRoot(ans)


从开始局面到目标局面的路径：
id：1，来自：None。空位在第 1 行，第 1 列
[[1 2 3]
 [8 0 4]
 [7 6 5]]
id：5，来自：1。空位在第 1 行，第 2 列
[[1 2 3]
 [8 4 0]
 [7 6 5]]
id：16，来自：5。空位在第 2 行，第 2 列
[[1 2 3]
 [8 4 5]
 [7 6 0]]
id：45，来自：16。空位在第 2 行，第 1 列
[[1 2 3]
 [8 4 5]
 [7 0 6]]


### 避免走回头路

从开始局面空位上移一步可以到局面 $s1$，从 $s1$ 如果下移一步又会回到开始局面。像这样来回走肯定不是最优答案的一部分。所以我们可以优化 move() 方法，每个居民生成能到达的局面时，避免回到来自的局面： 如果 ni, nj 是合法的，self.p 又存在的话，我们要保证 ni, nj != p.i, p.j


In [11]:
import numpy as np # 用到 numpy 的数组

# 定义一个叫 State 的类
class State:
    
    count = 0
    
    # 定义一个构造函数，用传进来的 b,i,j 构造一个局面
    def __init__(self, b, i, j, p):
        self.b = b
        self.i = i
        self.j = j
        self.p = p
        self.id = State.count
        State.count += 1
    
    # 把局面转换成一个字符串，方便打印输出
    def __str__(self):
        pid = None if self.p is None else self.p.id
        return "id：{0}，来自：{1}。空位在第 {2} 行，第 {3} 列\n{4}".format(self.id, pid, self.i,self.j,self.b)

    # 由当前局面按照 mv 移动一步后得到的局面, mv = 0,1,2,3 分别表示空位向上、右、下、左移动一步。
    def move(self, mv):
        di = [-1,1,0,0]
        dj = [0,0,-1,1]
        ni,nj = self.i+di[mv], self.j+dj[mv]
        
        if ni < 0 or ni > 2 or nj < 0 or nj > 2:
            return None
        
        # 避免回到来源局面
        if self.p is not None and ni == self.p.i and nj == self.p.j:
            return None
        
        b = np.copy(self.b) # 把局面复制一份，移动不会改变当前局面
        b[ni][nj],b[self.i][self.j] = b[self.i][self.j],b[ni][nj]
        return State(b,ni,nj,self)
    
    # 返回一个 list 记录由当前局面可以一步到达的所有局面
    def moves(self):
        r = []
        for mv in range(4):
            s = self.move(mv)
            if s is not None:
                r.append(s)
        return r
    
    # 检查 self 是否与 other 是同样局面
    def __eq__(self, other):
        if self.i != other.i or self.j != other.j:
            return False
        return np.array_equal(self.b, other.b)

# 创建目标局面
sF = State(b=np.array([[1,2,3],[8,4,5],[7,0,6]]), i=2, j=1, p=None)

# 创建初始局面，会调用构造函数 __init__
s1 = State(b=np.array([[1,2,3],[8,0,4],[7,6,5]]), i=1, j=1, p=None)


ans = BFS(s1, sF)

探索局面:0
id：1，来自：None。空位在第 1 行，第 1 列
[[1 2 3]
 [8 0 4]
 [7 6 5]]
探索局面:1
id：2，来自：1。空位在第 0 行，第 1 列
[[1 0 3]
 [8 2 4]
 [7 6 5]]
探索局面:2
id：3，来自：1。空位在第 2 行，第 1 列
[[1 2 3]
 [8 6 4]
 [7 0 5]]
探索局面:3
id：4，来自：1。空位在第 1 行，第 0 列
[[1 2 3]
 [0 8 4]
 [7 6 5]]
探索局面:4
id：5，来自：1。空位在第 1 行，第 2 列
[[1 2 3]
 [8 4 0]
 [7 6 5]]
探索局面:5
id：6，来自：2。空位在第 0 行，第 0 列
[[0 1 3]
 [8 2 4]
 [7 6 5]]
探索局面:6
id：7，来自：2。空位在第 0 行，第 2 列
[[1 3 0]
 [8 2 4]
 [7 6 5]]
探索局面:7
id：8，来自：3。空位在第 2 行，第 0 列
[[1 2 3]
 [8 6 4]
 [0 7 5]]
探索局面:8
id：9，来自：3。空位在第 2 行，第 2 列
[[1 2 3]
 [8 6 4]
 [7 5 0]]
探索局面:9
id：10，来自：4。空位在第 0 行，第 0 列
[[0 2 3]
 [1 8 4]
 [7 6 5]]
探索局面:10
id：11，来自：4。空位在第 2 行，第 0 列
[[1 2 3]
 [7 8 4]
 [0 6 5]]
探索局面:11
id：12，来自：5。空位在第 0 行，第 2 列
[[1 2 0]
 [8 4 3]
 [7 6 5]]
探索局面:12
id：13，来自：5。空位在第 2 行，第 2 列
[[1 2 3]
 [8 4 5]
 [7 6 0]]
探索局面:13
id：14，来自：6。空位在第 1 行，第 0 列
[[8 1 3]
 [0 2 4]
 [7 6 5]]
探索局面:14
id：15，来自：7。空位在第 1 行，第 2 列
[[1 3 4]
 [8 2 0]
 [7 6 5]]
探索局面:15
id：16，来自：8。空位在第 1 行，第 0 列
[[1 2 3]
 [0 6 4]
 [8 7 5]]
探索局面:16
id：17，来自：9。空位在第 

虽然只是简单的避免走回头路，我们可以看到，新的代码只需要探索 20 个局面就可以找到答案，而旧的需要 45 个节点！！！

### BFS 找到的第一个目标局面必然是步数最少的答案

### BFS 需要的内存与答案的长度成指数增长

在一个典型的树状结构里面，如果每个节点有 k 个子节点，那么树第 0 层只有 1 个节点；第一层有 k 个节点，第二层有 $k^2$ 个节点，第 h 层有 $k^h$ 个节点。由于 BFS 每探索一个节点就会把它的所有子节点加到队列 q 中。当探索玩 h-1 层的所有结点时，q 中记录着第 h 层的所有结点。如果运气好，答案是第 h 层最左边的，那么 q 的长度是 $k^h$。如果运气不好， 答案是第 h 层的最右边一个节点，那么 q 的长度是 $k^(h+1)-k$。


## 深度优先搜索 (Depth First Search)

先探索根节点，然后按照子节点的顺序探索每棵子树中的所有结点。在我们的例子里面，先探索 $s0$ 然后探索 $s1$ 这个子树中的所有结点，探索玩 $s1$ 子树以后才探索 $s2$ 子树。在探索 $s1$ 子树时，又是先探索它的根节点 $s1$，然后探索它的子树 $s5$ 与 $s6$。

实现 DFS 只需要对 BFS 做两处改动
1. 每次从 q 中拿最后一个而不是第一个 （q 是一个栈)
2. 每次把 f 能一步到达的子节点按照倒叙添加到 q 的尾部


In [ ]:
def DFS(s1,sF):
    q = [s1] # 用 list 来实现栈
    count = 0
    while len(q) > 0: # 栈里面还有待探索局面
        f = q.pop()  # 拿出栈中的最后一个局面
        print("探索局面:{0}".format(count))
        count += 1
        print(f)
        if f == sF:  # 调用 f.__eq__(sF) 检查 f 是否是目标局面
            return f
        q.extend(reversed(f.moves())) # 把 f 能一步到达的局面按照倒叙加到栈尾部
    return None

### 如果树的最大深度是 $H$ 那么 q 的大小最多是 $k * H$

DFS 与 BFS 相比最大的优势是需要内存空间很少。

### DFS 找到的第一个答案未必是最少步数

在我们的例子中，由于有环的存在，有可能 DFS 永远找不到答案。比如从开始局面起，上移、右移、下移、左移又回到了开始局面。所以用 DFS 求解问题：

1. 要么要记录已经探索过的局面，避免重复探索，但是就失去了 DFS 需要内存小的优势
2. 要么限制探索的深度，然后每次迭代逐步增加探索的深度直到找到答案,这叫做逐步加深。

### 逐步加深的深度优先搜索 (Iterative Deepening DFS)

1. ID-DFS 需要的内存与 DFS 一样多
2. ID-DFS 找到的第一个答案必然是最少步数的
3. 如果每个节点平均有 $k \ge 2$ 个子节点，ID-DFS 需要的时间最多是 BFS 的两倍

实现方法
1. 在 State 类添加一个 d 记录局面的深度
    1. 在 __init__ 中增加一个参数 d
    2. 在 move() 方法中设置新局面的 d 为 self.d + 1
2. 修改 DFS 增加一个 maxD 参数，只有深度不超过 maxD 的节点才加入栈中
3. 增加一个 ID_DFS 方法，maxD 从 0 开始，每调用一次 DFS 增加 maxD 直到找到答案

In [12]:
import numpy as np # 用到 numpy 的数组

# 定义一个叫 State 的类
class State:
    
    count = 0
    
    # 定义一个构造函数，用传进来的 b,i,j 构造一个局面
    def __init__(self, b, i, j, p, d=0):
        self.b = b
        self.i = i
        self.j = j
        self.p = p
        self.id = State.count
        State.count += 1
        self.d = d
    
    # 把局面转换成一个字符串，方便打印输出
    def __str__(self):
        pid = None if self.p is None else self.p.id
        return "id：{0}，来自：{1}。空位在第 {2} 行，第 {3} 列\n{4}".format(self.id, pid, self.i,self.j,self.b)

    # 由当前局面按照 mv 移动一步后得到的局面, mv = 0,1,2,3 分别表示空位向上、右、下、左移动一步。
    def move(self, mv):
        di = [-1,1,0,0]
        dj = [0,0,-1,1]
        ni,nj = self.i+di[mv], self.j+dj[mv]
        
        if ni < 0 or ni > 2 or nj < 0 or nj > 2:
            return None
        
        # 避免回到来源局面
        if self.p is not None and ni == self.p.i and nj == self.p.j:
            return None
        
        b = np.copy(self.b) # 把局面复制一份，移动不会改变当前局面
        b[ni][nj],b[self.i][self.j] = b[self.i][self.j],b[ni][nj]
        return State(b,ni,nj,self,self.d+1)
    
    # 返回一个 list 记录由当前局面可以一步到达的所有局面
    def moves(self):
        r = []
        for mv in range(4):
            s = self.move(mv)
            if s is not None:
                r.append(s)
        return r
    
    # 检查 self 是否与 other 是同样局面
    def __eq__(self, other):
        if self.i != other.i or self.j != other.j:
            return False
        return np.array_equal(self.b, other.b)

def DFS(s1,sF,maxD):
    q = [s1] # 用 list 来实现栈
    count = 0
    while len(q) > 0: # 栈里面还有待探索局面
        f = q.pop()  # 拿出栈中的最后一个局面
        print("探索局面:{0}".format(count))
        count += 1
        print(f)
        if f == sF:  # 调用 f.__eq__(sF) 检查 f 是否是目标局面
            return f
        if f.d < maxD: # 只有 depth <= maxD 的节点才添加到栈中
            q.extend(reversed(f.moves())) # 把 f 能一步到达的局面按照倒叙加到栈尾部
    return None

def ID_DFS(s1, sF):
    maxD = 0
    while True:
        ans = DFS(s1, sF, maxD)
        if ans is not None:
            return ans
        maxD += 1
    return None

# 创建目标局面
sF = State(b=np.array([[1,2,3],[8,4,5],[7,0,6]]), i=2, j=1, p=None, d=0)

# 创建初始局面，会调用构造函数 __init__
s1 = State(b=np.array([[1,2,3],[8,0,4],[7,6,5]]), i=1, j=1, p=None, d=0)

ans = ID_DFS(s1, sF)

path = findPathFromRoot(ans)


探索局面:0
id：1，来自：None。空位在第 1 行，第 1 列
[[1 2 3]
 [8 0 4]
 [7 6 5]]
探索局面:0
id：1，来自：None。空位在第 1 行，第 1 列
[[1 2 3]
 [8 0 4]
 [7 6 5]]
探索局面:1
id：2，来自：1。空位在第 0 行，第 1 列
[[1 0 3]
 [8 2 4]
 [7 6 5]]
探索局面:2
id：3，来自：1。空位在第 2 行，第 1 列
[[1 2 3]
 [8 6 4]
 [7 0 5]]
探索局面:3
id：4，来自：1。空位在第 1 行，第 0 列
[[1 2 3]
 [0 8 4]
 [7 6 5]]
探索局面:4
id：5，来自：1。空位在第 1 行，第 2 列
[[1 2 3]
 [8 4 0]
 [7 6 5]]
探索局面:0
id：1，来自：None。空位在第 1 行，第 1 列
[[1 2 3]
 [8 0 4]
 [7 6 5]]
探索局面:1
id：6，来自：1。空位在第 0 行，第 1 列
[[1 0 3]
 [8 2 4]
 [7 6 5]]
探索局面:2
id：10，来自：6。空位在第 0 行，第 0 列
[[0 1 3]
 [8 2 4]
 [7 6 5]]
探索局面:3
id：11，来自：6。空位在第 0 行，第 2 列
[[1 3 0]
 [8 2 4]
 [7 6 5]]
探索局面:4
id：7，来自：1。空位在第 2 行，第 1 列
[[1 2 3]
 [8 6 4]
 [7 0 5]]
探索局面:5
id：12，来自：7。空位在第 2 行，第 0 列
[[1 2 3]
 [8 6 4]
 [0 7 5]]
探索局面:6
id：13，来自：7。空位在第 2 行，第 2 列
[[1 2 3]
 [8 6 4]
 [7 5 0]]
探索局面:7
id：8，来自：1。空位在第 1 行，第 0 列
[[1 2 3]
 [0 8 4]
 [7 6 5]]
探索局面:8
id：14，来自：8。空位在第 0 行，第 0 列
[[0 2 3]
 [1 8 4]
 [7 6 5]]
探索局面:9
id：15，来自：8。空位在第 2 行，第 0 列
[[1 2 3]
 [7 8 4]
 [0 6 5]]
探索局面:10
id：9，来自：1。空位在第 1 

## 最好优先 (Best First Search)

有些节点比其它局面可能更快会到达目标局面，我们可以优先探索这些局面，希望比较快找到目标局面。


+ 因为一步只能改变一个数字的位置，所以如果一个局面 s 与目标局面有 k 个数字在不同位置，那么至少需要 $k$ 步才能到达目标局面。$k$ 叫做这个局面到目标的距离，记作 $dist(s,sF)$
+ 如果两个局面离目标的距离一样，比较浅的局面（已经移动步数比较少）最终找到的答案的总步数有可能更小，所以优先考虑。
+ 综上，对于一个局面可以定义 $p(s) = d(s) + dist(s,sF)$ 作为优先级，其中 d(s) 为局面 s 的深度

实现：
1. 在 State 类中增加一个 dist(self,other) 方法计算两个局面的距离
2. 搜索的时候，加入队列等待探索的局面按 $p(s)$ 从小到大排序, 具体用最小堆 Min-Heap 来实现


In [14]:
import numpy as np # 用到 numpy 的数组

# 定义一个叫 State 的类
class State:
    
    count = 0
    
    # 定义一个构造函数，用传进来的 b,i,j 构造一个局面
    def __init__(self, b, i, j, p, d=0):
        self.b = b
        self.i = i
        self.j = j
        self.p = p
        self.id = State.count
        State.count += 1
        self.d = d
    
    # 把局面转换成一个字符串，方便打印输出
    def __str__(self):
        pid = None if self.p is None else self.p.id
        return "id：{0}，来自：{1}。空位在第 {2} 行，第 {3} 列\n{4}".format(self.id, pid, self.i,self.j,self.b)

    # 由当前局面按照 mv 移动一步后得到的局面, mv = 0,1,2,3 分别表示空位向上、右、下、左移动一步。
    def move(self, mv):
        di = [-1,1,0,0]
        dj = [0,0,-1,1]
        ni,nj = self.i+di[mv], self.j+dj[mv]
        
        if ni < 0 or ni > 2 or nj < 0 or nj > 2:
            return None
        
        # 避免回到来源局面
        if self.p is not None and ni == self.p.i and nj == self.p.j:
            return None
        
        b = np.copy(self.b) # 把局面复制一份，移动不会改变当前局面
        b[ni][nj],b[self.i][self.j] = b[self.i][self.j],b[ni][nj]
        return State(b,ni,nj,self,self.d+1)
    
    # 返回一个 list 记录由当前局面可以一步到达的所有局面
    def moves(self):
        r = []
        for mv in range(4):
            s = self.move(mv)
            if s is not None:
                r.append(s)
        return r
    
    # 检查 self 是否与 other 是同样局面
    def __eq__(self, other):
        if self.i != other.i or self.j != other.j:
            return False
        return np.array_equal(self.b, other.b)

    def dist(self, other):
        count = np.sum(self.b != other.b)
        if count > 0:  # 当两个局面有不同时，忽略 0 的位置，因为只要有一个数字不同
            count -= 1
        return count

import minheap as mh
def BestFS(s1, sF):
    q = mh.MinHeap()
    q.push(s1.d + s1.dist(sF), s1) # 用 Min-Heap 实现优先队列
    count = 0
    while len(q) > 0: # 队列里面还有待探索局面
        hn = q.pop()  # 拿出优先级最小的一个
        f = hn.data
        print("探索局面:{0}, 优先级：{1}".format(count,hn.priority))
        count += 1
        print(f)
        if f == sF:  # 调用 f.__eq__(sF) 检查 f 是否是目标局面
            return f
        for s in f.moves(): # 把 f 能一步到达的局面加到队列尾部
            q.push(s.d + s.dist(sF), s)
    return None


# 创建目标局面
sF = State(b=np.array([[1,2,3],[8,4,5],[7,0,6]]), i=2, j=1, p=None, d=0)

# 创建初始局面，会调用构造函数 __init__
s1 = State(b=np.array([[1,2,3],[8,0,4],[7,6,5]]), i=1, j=1, p=None, d=0)

ans = BestFS(s1, sF)

path = findPathFromRoot(ans)


探索局面:0, 优先级：3
id：1，来自：None。空位在第 1 行，第 1 列
[[1 2 3]
 [8 0 4]
 [7 6 5]]
探索局面:1, 优先级：3
id：3，来自：1。空位在第 2 行，第 1 列
[[1 2 3]
 [8 6 4]
 [7 0 5]]
探索局面:2, 优先级：3
id：5，来自：1。空位在第 1 行，第 2 列
[[1 2 3]
 [8 4 0]
 [7 6 5]]
探索局面:3, 优先级：3
id：9，来自：5。空位在第 2 行，第 2 列
[[1 2 3]
 [8 4 5]
 [7 6 0]]
探索局面:4, 优先级：3
id：10，来自：9。空位在第 2 行，第 1 列
[[1 2 3]
 [8 4 5]
 [7 0 6]]
从开始局面到目标局面的路径：
id：1，来自：None。空位在第 1 行，第 1 列
[[1 2 3]
 [8 0 4]
 [7 6 5]]
id：5，来自：1。空位在第 1 行，第 2 列
[[1 2 3]
 [8 4 0]
 [7 6 5]]
id：9，来自：5。空位在第 2 行，第 2 列
[[1 2 3]
 [8 4 5]
 [7 6 0]]
id：10，来自：9。空位在第 2 行，第 1 列
[[1 2 3]
 [8 4 5]
 [7 0 6]]


在这个例子里，BestFS 只探索了 4 个局面就找到了答案！！！

最好优先与 BFS 类似，最坏情况下需要的内存空间也是与答案的步数呈指数增长。

### A* 算法
在我们的例子里，$p(s)$ 实际上是所有从根节点经过 $s$ 到目标局面的路径的长度的下界，所以这个 BestFS 找到的第一个解一定是步数最少的。这个算法在 AI 里面也叫 A* 算法。



## 逐步迭代加深 BestFS 算法

我们可以借鉴 ID_DFS 想法, 我们可以逐步迭代加深 BestFS：
1. 每次迭代用 DFS 搜索优先级不超过 maxP 的局面
2. 每次迭代增加 maxP 直到找到第一个答案

In [18]:
def DFS2(s1,sF,maxD):
    q = [s1] # 用 list 来实现栈
    count = 0
    while len(q) > 0: # 栈里面还有待探索局面
        f = q.pop()  # 拿出栈中的最后一个局面
        print("探索局面:{0}".format(count))
        count += 1
        print(f)
        if f == sF:  # 调用 f.__eq__(sF) 检查 f 是否是目标局面
            return f
        for s in f.moves():
            p = s.d + s.dist(sF) # 只有优先级 <= maxP 的节点才添加到栈中
            if p <= maxD:
                q.append(s)
    return None

def IDBestFS(s1, sF):
    maxP = 0
    while True:
        print("maxP: {0}".format(maxP))
        ans = DFS2(s1, sF, maxP)
        if ans is not None:
            return ans
        maxP += 1
    return None

# 创建目标局面
sF = State(b=np.array([[1,2,3],[8,4,5],[7,0,6]]), i=2, j=1, p=None, d=0)

# 创建初始局面，会调用构造函数 __init__
s1 = State(b=np.array([[1,2,3],[8,0,4],[7,6,5]]), i=1, j=1, p=None, d=0)

ans = IDBestFS(s1, sF)

path = findPathFromRoot(ans)


maxP: 0
探索局面:0
id：56，来自：None。空位在第 1 行，第 1 列
[[1 2 3]
 [8 0 4]
 [7 6 5]]
maxP: 1
探索局面:0
id：56，来自：None。空位在第 1 行，第 1 列
[[1 2 3]
 [8 0 4]
 [7 6 5]]
maxP: 2
探索局面:0
id：56，来自：None。空位在第 1 行，第 1 列
[[1 2 3]
 [8 0 4]
 [7 6 5]]
maxP: 3
探索局面:0
id：56，来自：None。空位在第 1 行，第 1 列
[[1 2 3]
 [8 0 4]
 [7 6 5]]
探索局面:1
id：72，来自：56。空位在第 1 行，第 2 列
[[1 2 3]
 [8 4 0]
 [7 6 5]]
探索局面:2
id：74，来自：72。空位在第 2 行，第 2 列
[[1 2 3]
 [8 4 5]
 [7 6 0]]
探索局面:3
id：75，来自：74。空位在第 2 行，第 1 列
[[1 2 3]
 [8 4 5]
 [7 0 6]]
从开始局面到目标局面的路径：
id：56，来自：None。空位在第 1 行，第 1 列
[[1 2 3]
 [8 0 4]
 [7 6 5]]
id：72，来自：56。空位在第 1 行，第 2 列
[[1 2 3]
 [8 4 0]
 [7 6 5]]
id：74，来自：72。空位在第 2 行，第 2 列
[[1 2 3]
 [8 4 5]
 [7 6 0]]
id：75，来自：74。空位在第 2 行，第 1 列
[[1 2 3]
 [8 4 5]
 [7 0 6]]


在我们的例子里，因为我们的 $p(s)$ 是答案步数的下界，所以找到的第一个解就是步数最少的解。所以我成这个算法为 IDA* （逐步迭代加深 A*）算法。它的优点：

1. IDA* 与 DFS 一样需要的内存与答案的步数成正比
2. IDA* 最多只需要 BestFS 两倍的时间，而且每个节点的平均子节点数 $k$ 越大， IDA* 需要的时间与 BestFS 越接近
3. 不需要 Min-Heap !!



## 分支定界 (Branch and Bound)：

另外一个加速搜索的办法是利用已经找到的解作为上界，一个局面如果它的 $p(s)$ 超过了上界，它的子树中就一定不会有更好的解。[C代码](https://www.geeksforgeeks.org/8-puzzle-problem-using-branch-and-bound/)

## 还可以结合IDA* 与分支定界进一步加速搜：[参考](https://ieeexplore.ieee.org/document/6216460)


## 打印开头状态图的代码

把输出贴到 dot 文件在[线编辑器](http://magjac.com/graphviz-visual-editor/)

In [2]:
import numpy as np # 用到 numpy 的数组

# 定义一个叫 State 的类
class State:
    
    count = 0
    
    # 定义一个构造函数，用传进来的 b,i,j 构造一个局面
    def __init__(self, b, i, j, p, d=0):
        self.b = b
        self.i = i
        self.j = j
        self.p = p
        self.id = State.count
        State.count += 1
        self.d = d
    
    # 把局面转换成一个字符串，方便打印输出
    def __str__(self):
        pid = None if self.p is None else self.p.id
        return "id：{0}，来自：{1}。空位在第 {2} 行，第 {3} 列\n{4}".format(self.id, pid, self.i,self.j,self.b)

    # 由当前局面按照 mv 移动一步后得到的局面, mv = 0,1,2,3 分别表示空位向上、右、下、左移动一步。
    def move(self, mv):
        di = [-1,1,0,0]
        dj = [0,0,-1,1]
        ni,nj = self.i+di[mv], self.j+dj[mv]
        
        if ni < 0 or ni > 2 or nj < 0 or nj > 2:
            return None
        
        # 避免回到来源局面
        if self.p is not None and ni == self.p.i and nj == self.p.j:
            return None
        
        b = np.copy(self.b) # 把局面复制一份，移动不会改变当前局面
        b[ni][nj],b[self.i][self.j] = b[self.i][self.j],b[ni][nj]
        return State(b,ni,nj,self,self.d+1)
    
    # 返回一个 list 记录由当前局面可以一步到达的所有局面
    def moves(self):
        r = []
        for mv in range(4):
            s = self.move(mv)
            if s is not None:
                r.append(s)
        return r
    
    # 检查 self 是否与 other 是同样局面
    def __eq__(self, other):
        if self.i != other.i or self.j != other.j:
            return False
        return np.array_equal(self.b, other.b)

    def dist(self, other):
        count = np.sum(self.b != other.b)
        if count > 0:  # 当两个局面有不同时，忽略 0 的位置，因为只要有一个数字不同
            count -= 1
        return count
    
    def toDotNode(self):
        cells = []
        for j in range(3):
            for i in range(3):
                if self.b[i][j] == 0:
                    cells.append(' ')
                else:
                    cells.append(self.b[i][j])
        
        nstr = "s{0} [label=\"s{0} | {{{1}|{2}|{3}}} | {{{4}|{5}|{6}}} | {{{7}|{8}|{9}}}\"];".format(self.id,
            cells[0],cells[1],cells[2],cells[3],cells[4],cells[5],cells[6],cells[7],cells[8])
        if self.p is None:
            return nstr;
        return nstr + "\ns{0}:s -> s{1}:n;".format(self.p.id, self.id)
    
# 创建目标局面
sF = State(b=np.array([[1,2,3],[8,4,5],[7,0,6]]), i=2, j=1, p=None, d=0)

# 创建初始局面，会调用构造函数 __init__
s1 = State(b=np.array([[1,2,3],[8,0,4],[7,6,5]]), i=1, j=1, p=None, d=0)

print("digraph states {")
print("    splines=false;")
print("    node [shape=record];")
print("    ",s1.toDotNode())
lst = s1.moves()
lst1 =[]
for s in lst:
    print("    ",s.toDotNode())
    lst1.extend(s.moves())

lst2 = []
for s1 in lst1:
    print("    ",s1.toDotNode())
    lst2.extend(s1.moves())
    
for s2 in lst2:
    print("    ",s2.toDotNode())
print("}")


digraph states {
    splines=false;
    node [shape=record];
     s1 [label="s1 | {1|8|7} | {2| |6} | {3|4|5}"];
     s2 [label="s2 | {1|8|7} | { |2|6} | {3|4|5}"];
s1:s -> s2:n;
     s3 [label="s3 | {1|8|7} | {2|6| } | {3|4|5}"];
s1:s -> s3:n;
     s4 [label="s4 | {1| |7} | {2|8|6} | {3|4|5}"];
s1:s -> s4:n;
     s5 [label="s5 | {1|8|7} | {2|4|6} | {3| |5}"];
s1:s -> s5:n;
     s6 [label="s6 | { |8|7} | {1|2|6} | {3|4|5}"];
s2:s -> s6:n;
     s7 [label="s7 | {1|8|7} | {3|2|6} | { |4|5}"];
s2:s -> s7:n;
     s8 [label="s8 | {1|8| } | {2|6|7} | {3|4|5}"];
s3:s -> s8:n;
     s9 [label="s9 | {1|8|7} | {2|6|5} | {3|4| }"];
s3:s -> s9:n;
     s10 [label="s10 | { |1|7} | {2|8|6} | {3|4|5}"];
s4:s -> s10:n;
     s11 [label="s11 | {1|7| } | {2|8|6} | {3|4|5}"];
s4:s -> s11:n;
     s12 [label="s12 | {1|8|7} | {2|4|6} | { |3|5}"];
s5:s -> s12:n;
     s13 [label="s13 | {1|8|7} | {2|4|6} | {3|5| }"];
s5:s -> s13:n;
     s14 [label="s14 | {8| |7} | {1|2|6} | {3|4|5}"];
s6:s -> s14:n;
     s15 [labe